apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  labels:
    app: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: blog
        image: ghost:latest
        ports:
        - containerPort: 2368
        env:
        - name: url
          value: http://10.193.162.113:30081
        volumeMounts:
        - mountPath: /var/lib/ghost/content
          name: content
      imagePullSecrets:
      - name: bala-secret
      volumes:
      - name: content
        persistentVolumeClaim:
          claimName: blog-content-from-snap
